Feedback
MIEE-ACS/domashnee-zadanie-no3-Albinaf pull request #1
Opened 2020-10-22 07:03 UTC by SergeyTeslov

:wave:! GitHub Classroom created this pull request as a place for your teacher to leave feedback on your work. It will update automatically. **Don’t close or merge this pull request**, unless you’re instructed to do so by your teacher.

In this pull request, your teacher can leave comments and feedback on your code. Click the **Subscribe** button to be notified if that happens.

Click the **Files changed** or **Commits** tab to see all of the changes pushed to `master` since the assignment started. Your teacher can see this too.

<details>
<summary>
<strong>Notes for teachers</strong>
</summary>

Use this PR to leave feedback. Here are some tips:

- Click the **Files changed** tab to see all of the changes pushed to `master` since the assignment started. To leave comments on specific lines of code, put your cursor over a line of code and click the blue **+** (plus sign). To learn more about comments, read “[Commenting on a pull request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/commenting-on-a-pull-request)”.
- Click the **Commits** tab to see the commits pushed to `master`. Click a commit to see specific changes.
- If you turned on autograding, then click the **Checks** tab to see the results.
- This page is an overview. It shows commits, line comments, and general comments. You can leave a general comment below.

For more information about this pull request, read “[Leaving assignment feedback in GitHub](https://classroom.github.com/help/leaving-feedback-in-github)”.
</details>

2020-10-25 11:45 UTC, d-makarenko requested changes

2020-10-25 11:45 UTC, d-makarenko commented on WpfApp1/MainWindow.xaml.cs
> +            string alfphabet = "АБВГДЕЖЗИКЛМНОПРСТУФХЦЧШЩЬЪЭЮЯ";
Что случилось с алфавитом? 
Я могу еще понять, когда Ё за букву не считают, но куда Ы, Й делись?

2020-10-25 11:45 UTC, d-makarenko commented on WpfApp1/MainWindow.xaml.cs
> +                        while (t >= m)
Допустим мы зашифровали текст. Но после этого, хотелось бы его расшифровать. Логично было бы ввести ключ со знаком минус, но программа в этом случае крашится.

2020-10-25 11:45 UTC, d-makarenko commented on WpfApp1/MainWindow.xaml.cs
> +            string s = tb.Text;
Вместо того, чтобы требовать от пользователя ввода ЗАПИСЫВАТЬ ВСЕ КАПСОМ можно использовать метод ToUpper()
Хотя конечно было бы правильнее сохранять регистр.

2020-10-25 11:45 UTC, d-makarenko commented on WpfApp1/MainWindow.xaml.cs
> +                    if (s[i] == alfphabet[j])
И еще мне не нравится то, что пропадают знаки препинания, может их можно как то сохранить?

2020-10-29 07:50 UTC, SergeyTeslov commented on WpfApp1/MainWindow.xaml.cs
> +            string cyrillic_s = "абвгдеёжзийклмнопрстуфхцчшщьъэюя";
букву ы я  всё же не нашёл.
Программа работает, шифрует и дешифрует.
Заглавные буквы и знаки пунктуации обрабатывает корректно.

2020-10-29 07:50 UTC, SergeyTeslov commented
Оценка: 5/5

2020-10-29 07:51 UTC, merged